name: Update Store Data

permissions:
  contents: write

on:
  schedule:
    - cron: '0 6 * * *'  # Dagligt kl 06:00 UTC
  workflow_dispatch:      # Manuel trigger

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Update store data
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        GOOGLE_SHEET_NAME: ${{ secrets.GOOGLE_SHEET_NAME }}
      run: npm run update
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

        # Configure git to use token for authentication
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

        # Pull latest changes first
        git pull --rebase origin main

        # Add and commit if there are changes
        git add stores*.json stores*.csv
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore: update store data [skip ci]"
          git push origin main
        fi
